# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='library',
            unique_together=set([('username', 'book_id')]),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['username'], name='book_id'),
        ),
    ]
