# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headspace', '0003_auto_20171006_2018'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='library',
            name='book',
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['user', 'book'], name='user_book_idx'),
        ),
    ]
