# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('tee_slug', models.CharField(max_length=128)),
                ('tee_size', models.CharField(max_length=8)),
                ('amount', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billing_address_city', models.CharField(max_length=128)),
                ('billing_address_country', models.CharField(max_length=128)),
                ('billing_address_country_code', models.CharField(max_length=128)),
                ('billing_address_line1', models.CharField(max_length=128)),
                ('billing_address_state', models.CharField(max_length=128)),
                ('billing_address_zip', models.CharField(max_length=128)),
                ('billing_name', models.CharField(max_length=128)),
                ('shipping_address_city', models.CharField(max_length=128)),
                ('shipping_address_country', models.CharField(max_length=128)),
                ('shipping_address_country_code', models.CharField(max_length=128)),
                ('shipping_address_line1', models.CharField(max_length=128)),
                ('shipping_address_state', models.CharField(max_length=128)),
                ('shipping_address_zip', models.CharField(max_length=128)),
                ('shipping_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=128)),
                ('receipt_email', models.CharField(max_length=128)),
                ('stripe_id', models.CharField(max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tees.Order')),
            ],
        ),
    ]
