# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=128)),
                ('receipt_email', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tee',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
