# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tees', '0002_auto_20170924_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tee',
            new_name='tee_slug',
        ),
        migrations.RemoveField(
            model_name='stripecharge',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stripecharge',
            name='source',
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tees.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecharge',
            name='stripe_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
