# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tees', '0003_auto_20170924_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stripecharge',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
